name: Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          pytest --cov=backend/app --cov-report=term-missing --cov-report=html backend/app/tests/test_integration_v1.py

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: html-coverage-report
          path: htmlcov/
