name: Run Microservices Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies for cart_service
      run: pip install -r backend/cart_service/requirements.txt

    - name: Install dependencies for product_service
      run: pip install -r backend/product_service/requirements.txt
      
    - name: Install dependencies for user_service
      run: pip install -r backend/user_service/requirements.txt

    - name: Run tests
      run: pytest test/
